"""SQLModel models for the Todo API.

The ``Todo`` model represents a single todo item stored in the SQLite
database. It inherits from ``SQLModel`` which provides both Pydantic validation
and ORM capabilities.
"""

from typing import Optional
from sqlmodel import Field, SQLModel


class TodoBase(SQLModel):
    """Base attributes shared between create and read models."""

    title: str
    description: Optional[str] = None
    completed: bool = False


class Todo(TodoBase, table=True):
    """Database model for a todo item.

    The ``id`` field is an auto‑incrementing primary key generated by SQLite.
    """

    id: Optional[int] = Field(default=None, primary_key=True)


class TodoCreate(TodoBase):
    """Schema used when creating a new todo item via the API."""

    pass


class TodoRead(TodoBase):
    """Schema returned from the API when reading todo items."""

    id: int


class TodoUpdate(SQLModel):
    """Schema for partial updates of a todo item.

    All fields are optional so that a client can send only the fields it
    wishes to modify.
    """

    title: Optional[str] = None
    description: Optional[str] = None
    completed: Optional[bool] = None
