# app/models.py
"""Data models for the Todo application.

We use **SQLModel**, which combines SQLAlchemy's ORM capabilities with
Pydantic's data validation. Two model classes are defined:

* ``Todo`` – the ORM model representing a row in the ``todos`` table.
* ``TodoCreate`` – a Pydantic model used for request bodies when creating a
  new todo. It inherits from ``TodoBase`` but excludes the ``id`` field.
"""

from typing import Optional
from sqlmodel import Field, SQLModel

class TodoBase(SQLModel):
    """Base attributes shared by all Todo models."""

    title: str = Field(index=True, description="Short title of the todo item")
    description: Optional[str] = Field(
        default=None, description="Longer description of the todo item"
    )
    completed: bool = Field(default=False, description="Completion status")

class Todo(TodoBase, table=True):
    """SQLModel ORM model representing a Todo record in the database."""

    id: Optional[int] = Field(
        default=None, primary_key=True, description="Auto‑generated primary key"
    )

class TodoCreate(TodoBase):
    """Model used for creating a new Todo via the API.

    ``id`` is omitted because it is generated by the database.
    """

    pass

class TodoRead(TodoBase):
    """Model used for reading Todo data from the API.

    Includes the ``id`` field so that clients can reference the resource.
    """

    id: int
